export const MERGE_PATH = (...path: string[]) => path.join('/')
export const ROOT_PATH = '/'
export const LOGIN_PATH = '/login'
export const FORGOT_PASSWORD_PATH = '/forgot-password'
export const RESET_PASSWORD_PATH = '/reset-password'
export const REGISTER_PATH = '/register'
export const DASHBOARD_PATH = '/dashboard'
export const ACCOUNT_PATH = '/account'
export const PRIVACY_POLICIES_PATH = '/privacy-policies'
export const ASSESSMENT_PATH = '/assessment'
export const PROFILE_PATH = '/profile'
export const BOOKING_PATH = '/booking'
export const BOOKING_REPORT_PATH = '/booking-report'
export const MY_BOOKING_PATH = '/my-booking'
export const EQUIPMENT_PATH = '/equipment'
