export const MERGE_PATH = (...path: string[]) => path.join('/')
export const ROOT_PATH = '/'
export const LOGIN_PATH = '/login'
export const FORGOT_PASSWORD_PATH = '/forgot-password'
export const RESET_PASSWORD_PATH = '/reset-password'
export const RESET_PASSWORD_SUCCESS_PATH = '/reset-password/success'
export const REGISTER_PATH = '/register'
export const REGISTER_SUCCESS_PATH = '/register/success'
export const DASHBOARD_PATH = '/dashboard'
export const ACCOUNT_PATH = '/account'
export const PRIVACY_POLICIES_PATH = '/privacy-policies'
export const ASSESSMENT_PATH = '/assessment'